CREATE TABLE IF NOT EXISTS INGESTION_RUNS (
    RUN_ID                  VARCHAR NOT NULL,
    SOURCE_CHECKSUM         VARCHAR NOT NULL,
    FILE_COUNT              NUMBER(38, 0) NOT NULL,
    RECORD_COUNT            NUMBER(38, 0) NOT NULL,
    UNIQUE_EVENT_COUNT      NUMBER(38, 0) NOT NULL,
    REJECTED_COUNT          NUMBER(38, 0) NOT NULL,
    COMPLETED_AT            TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_INGESTION_RUNS
        PRIMARY KEY (RUN_ID),

    CONSTRAINT UK_INGESTION_SOURCE_CHECKSUM
        UNIQUE (SOURCE_CHECKSUM)
);