CREATE TABLE IF NOT EXISTS INGESTION_RUNS (
    RUN_ID STRING PRIMARY KEY,
    SOURCE_CHECKSUM STRING NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    VALID_EVENT_COUNT NUMBER DEFAULT 0,
    REJECTED_EVENT_COUNT NUMBER DEFAULT 0,
    STATUS STRING NOT NULL,
    ERROR_MESSAGE STRING
);
