CREATE TABLE IF NOT EXISTS WORK_ORDER_EVENTS (
    EVENT_ID                VARCHAR NOT NULL,
    WORK_ORDER_ID           VARCHAR NOT NULL,
    CLIENT_ID               VARCHAR NOT NULL,
    EVENT_TYPE              VARCHAR NOT NULL,
    EVENT_TIMESTAMP_UTC     TIMESTAMP_TZ NOT NULL,
    UPDATED_AT_UTC          TIMESTAMP_TZ NOT NULL,
    PRIORITY                VARCHAR NOT NULL,
    TECHNICIAN_ID           VARCHAR NOT NULL,
    STORE_ID                VARCHAR NOT NULL,
    REGION                  VARCHAR NOT NULL,
    LABOR_MINUTES           NUMBER(10, 0) NOT NULL,
    SOURCE_SYSTEM           VARCHAR NOT NULL,
    SOURCE_FILE             VARCHAR,
    SOURCE_ROW_NUMBER       NUMBER(38, 0),
    PAYLOAD_HASH            VARCHAR NOT NULL,
    RAW_PAYLOAD             VARIANT,
    LAST_SEEN_AT            TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_WORK_ORDER_EVENTS
        PRIMARY KEY (EVENT_ID)
);