CREATE TABLE IF NOT EXISTS REJECTED_RECORDS (
    REJECTION_ID NUMBER AUTOINCREMENT,
    RUN_ID STRING NOT NULL,
    SOURCE_FILE STRING NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    REASON STRING NOT NULL,
    RAW_PAYLOAD STRING,
    REJECTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);