CREATE TABLE IF NOT EXISTS REJECTED_RECORDS (
    RUN_ID                  VARCHAR NOT NULL,
    SOURCE_FILE             VARCHAR,
    SOURCE_ROW_NUMBER       NUMBER(38, 0),
    EVENT_ID                VARCHAR,
    WORK_ORDER_ID           VARCHAR,
    REASON                  VARCHAR NOT NULL,
    RAW_RECORD              VARCHAR,
    REJECTED_AT             TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
