CREATE OR REPLACE VIEW WORK_ORDER_SUMMARY AS
WITH ordered AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY WORK_ORDER_ID ORDER BY EVENT_TIMESTAMP_UTC DESC, UPDATED_AT_UTC DESC, EVENT_ID DESC) AS rn
    FROM WORK_ORDER_EVENTS
), agg AS (
    SELECT WORK_ORDER_ID,
           MAX_BY(CLIENT_ID, EVENT_TIMESTAMP_UTC) AS CLIENT_ID,
           MAX_BY(STORE_ID, EVENT_TIMESTAMP_UTC) AS STORE_ID,
           MAX_BY(TECHNICIAN_ID, EVENT_TIMESTAMP_UTC) AS TECHNICIAN_ID,
           MAX_BY(PRIORITY, EVENT_TIMESTAMP_UTC) AS PRIORITY,
           MIN(IFF(EVENT_TYPE='OPENED', EVENT_TIMESTAMP_UTC, NULL)) AS OPENED_TIMESTAMP,
           MAX(IFF(EVENT_TYPE='CLOSED', EVENT_TIMESTAMP_UTC, NULL)) AS CLOSED_TIMESTAMP,
           MAX_BY(EVENT_TYPE, EVENT_TIMESTAMP_UTC) AS LAST_EVENT_TYPE,
           SUM(CASE WHEN EVENT_TYPE='WORK_COMPLETED' THEN COALESCE(LABOR_MINUTES,0) ELSE 0 END) AS TOTAL_LABOR_MINUTES,
           COUNT(*) AS EVENT_COUNT,
           COUNT_IF(EVENT_TYPE='REOPENED') AS REOPEN_COUNT,
           MAX(UPDATED_AT_UTC) AS LAST_UPDATED_TIMESTAMP
    FROM WORK_ORDER_EVENTS
    GROUP BY WORK_ORDER_ID
)
SELECT WORK_ORDER_ID, CLIENT_ID, STORE_ID, TECHNICIAN_ID, PRIORITY,
       OPENED_TIMESTAMP, CLOSED_TIMESTAMP,
       CASE LAST_EVENT_TYPE WHEN 'CLOSED' THEN 'CLOSED' WHEN 'REOPENED' THEN 'REOPENED'
            WHEN 'OPENED' THEN 'OPEN' WHEN 'WORK_COMPLETED' THEN 'COMPLETED'
            WHEN 'WORK_STARTED' THEN 'IN_PROGRESS' ELSE LAST_EVENT_TYPE END AS CURRENT_STATUS,
       TOTAL_LABOR_MINUTES, EVENT_COUNT, REOPEN_COUNT,
       IFF(OPENED_TIMESTAMP IS NOT NULL AND CLOSED_TIMESTAMP IS NOT NULL AND CLOSED_TIMESTAMP >= OPENED_TIMESTAMP,
           DATEDIFF('second', OPENED_TIMESTAMP, CLOSED_TIMESTAMP)/3600.0, NULL) AS RESOLUTION_HOURS,
       LAST_UPDATED_TIMESTAMP
FROM agg;
