CREATE OR REPLACE VIEW WORK_ORDER_SUMMARY AS
WITH SUMMARY AS (
    SELECT
        WORK_ORDER_ID,
        MAX(CLIENT_ID) AS CLIENT_ID,
        MAX(STORE_ID) AS STORE_ID,
        MAX_BY(TECHNICIAN_ID, EVENT_TIMESTAMP_UTC) AS TECHNICIAN_ID,
        MAX_BY(PRIORITY, EVENT_TIMESTAMP_UTC) AS PRIORITY,
        MIN(IFF(EVENT_TYPE = 'OPENED', EVENT_TIMESTAMP_UTC, NULL)) AS OPEN_TIMESTAMP,
        MAX(IFF(EVENT_TYPE = 'CLOSED', EVENT_TIMESTAMP_UTC, NULL)) AS CLOSE_TIMESTAMP,
        MAX_BY(EVENT_TYPE, EVENT_TIMESTAMP_UTC) AS CURRENT_STATUS,
        SUM(LABOR_MINUTES) AS TOTAL_LABOR_MINUTES,
        COUNT(*) AS EVENT_COUNT,
        COUNT_IF(EVENT_TYPE = 'REOPENED') AS REOPEN_COUNT
    FROM WORK_ORDER_EVENTS
    GROUP BY WORK_ORDER_ID
)
SELECT
    WORK_ORDER_ID,
    CLIENT_ID,
    STORE_ID,
    TECHNICIAN_ID,
    PRIORITY,
    OPEN_TIMESTAMP,
    CLOSE_TIMESTAMP,
    CURRENT_STATUS,
    TOTAL_LABOR_MINUTES,
    EVENT_COUNT,
    REOPEN_COUNT,
    IFF(
        OPEN_TIMESTAMP IS NOT NULL AND CLOSE_TIMESTAMP IS NOT NULL,
        DATEDIFF('second', OPEN_TIMESTAMP, CLOSE_TIMESTAMP) / 3600.0,
        NULL
    ) AS RESOLUTION_HOURS
FROM SUMMARY;
