CREATE OR REPLACE VIEW ANALYSIS_TECHNICIAN_CLOSE_RANK AS
SELECT TECHNICIAN_ID, COUNT(*) AS CLOSED_WORK_ORDER_COUNT,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS TECHNICIAN_RANK
FROM WORK_ORDER_SUMMARY WHERE CURRENT_STATUS = 'CLOSED'
GROUP BY TECHNICIAN_ID;
