CREATE OR REPLACE VIEW ANALYSIS_TECHNICIAN_CLOSE_RANK AS
SELECT TECHNICIAN_ID, COUNT(*) AS CLOSED_WORK_ORDER_COUNT,
       DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS CLOSE_RANK
FROM WORK_ORDER_SUMMARY
WHERE CURRENT_STATUS='CLOSED' AND TECHNICIAN_ID IS NOT NULL
GROUP BY TECHNICIAN_ID;
