CREATE OR REPLACE VIEW ANALYSIS_REOPEN_RATE AS
SELECT 100.0 * COUNT_IF(CURRENT_STATUS = 'CLOSED' AND REOPEN_COUNT > 0)
       / NULLIF(COUNT_IF(CURRENT_STATUS = 'CLOSED'), 0)
       AS REOPENED_CLOSED_WO_PERCENT
FROM WORK_ORDER_SUMMARY;
