CREATE OR REPLACE VIEW ANALYSIS_WEEKLY_COMPLETED AS
SELECT DATE_TRUNC('WEEK', CLOSE_TIMESTAMP) AS WEEK_START,
       COUNT(*) AS COMPLETED_WORK_ORDER_COUNT,
       AVG(RESOLUTION_HOURS) AS AVG_RESOLUTION_HOURS
FROM WORK_ORDER_SUMMARY
WHERE CURRENT_STATUS = 'CLOSED' AND CLOSE_TIMESTAMP IS NOT NULL
GROUP BY DATE_TRUNC('WEEK', CLOSE_TIMESTAMP);
