CREATE OR REPLACE VIEW ANALYSIS_WEEKLY_COMPLETED AS
SELECT DATE_TRUNC('WEEK', CLOSED_TIMESTAMP) AS WEEK_START,
       COUNT(*) AS COMPLETED_WORK_ORDERS,
       AVG(RESOLUTION_HOURS) AS AVERAGE_RESOLUTION_HOURS
FROM WORK_ORDER_SUMMARY
WHERE CURRENT_STATUS='CLOSED'
GROUP BY 1;




