CREATE TABLE IF NOT EXISTS SILVER_STORES (
    store_id STRING PRIMARY KEY, client_id STRING NOT NULL, store_number STRING NOT NULL,
    region STRING, active_flag BOOLEAN, last_seen_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
