CREATE OR REPLACE VIEW ANALYSIS_ABNORMAL_SEQUENCES AS
WITH ordered AS (
    SELECT WORK_ORDER_ID, EVENT_TYPE, EVENT_TIMESTAMP_UTC,
           LAG(EVENT_TYPE) OVER (PARTITION BY WORK_ORDER_ID ORDER BY EVENT_TIMESTAMP_UTC, UPDATED_AT_UTC, EVENT_ID) AS PREVIOUS_EVENT_TYPE
    FROM WORK_ORDER_EVENTS
)
SELECT WORK_ORDER_ID, PREVIOUS_EVENT_TYPE, EVENT_TYPE, EVENT_TIMESTAMP_UTC
FROM ordered
WHERE (PREVIOUS_EVENT_TYPE='WORK_COMPLETED' AND EVENT_TYPE='WORK_STARTED')
   OR (PREVIOUS_EVENT_TYPE='CLOSED' AND EVENT_TYPE IN ('WORK_STARTED','OPENED','ASSIGNED'))
   OR (PREVIOUS_EVENT_TYPE='OPENED' AND EVENT_TYPE='REOPENED')
   OR (PREVIOUS_EVENT_TYPE='WORK_STARTED' AND EVENT_TYPE='REOPENED');