CREATE TABLE IF NOT EXISTS SILVER_TECHNICIANS (
    technician_id STRING PRIMARY KEY, technician_name STRING NOT NULL, home_region STRING,
    active_flag BOOLEAN, last_seen_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
